server:
  port: 8081

spring:
  application:
    name: customers-ms

  datasource:
    url: jdbc:oracle:thin:@//localhost:11521/FREEPDB1
    username: CUSTOMERS
    password: customers
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.OracleDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

app:
  cors:
    allowed-origins: "http://localhost:4200,http://localhost:5173,http://localhost:8080"
