server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      routes:
        # ---- Customers: mantiene StripPrefix=1 (el MS recibe /createcustomer, /findcustomerbyid/**)
        - id: customers
          uri: lb://customers
          predicates:
            - Path=/customer/**
          filters:
            - StripPrefix=1

        # ---- Orders: SIN StripPrefix (el MS recibe /order/createorder, /order/updateorderstatus, /order/findorderbycustomerid/**)
        - id: orders
          uri: lb://orders
          predicates:
            - Path=/order/**

      globalcors:
        corsConfigurations:
          "[/**]":
            allowedOrigins: "http://localhost:5173,http://localhost:4200,http://localhost:8080"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
