-- Crea el esquema EXACTAMENTE como lo usa tu app
ALTER SESSION SET CONTAINER = FREEPDB1;

CREATE USER CUSTOMERS IDENTIFIED BY customers
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  QUOTA UNLIMITED ON USERS;

GRANT CREATE SESSION, CONNECT, RESOURCE TO CUSTOMERS;
GRANT CREATE TABLE, CREATE SEQUENCE, CREATE TRIGGER TO CUSTOMERS;
